

## Get a List of People

GET http://localhost:1337/people HTTP/1.1
Accept: application/json

### Adding a person

POST http://localhost:1337/people HTTP/1.1
Accept: application/json
Content-Type: application/json

### Getting a single person
GET http://localhost:1337/people/1 HTTP/1.1
Accept: application/json